// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 CAB Ingénierie / Christophe ABOULICAM
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/architecture',
        'concepts/mcp-gateway',
        'concepts/gitops',
        'concepts/multi-tenant',
        'concepts/mcp-gateway-positioning',
        'concepts/uac',
      ],
    },
    {
      type: 'category',
      label: 'Enterprise',
      link: {
        type: 'generated-index',
        description: 'Enterprise features, security, compliance, and support for STOA Platform.',
      },
      items: [
        'enterprise/use-cases',
        'enterprise/security-compliance',
        'enterprise/support',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/hybrid',
        'deployment/prerequisites',
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [
        'admin/installation',
        'admin/keycloak',
        'admin/monitoring',
        'admin/backup-recovery',
        'admin/upgrade',
        'admin/security-hardening',
        'admin/openshift',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/quick-start',
        'guides/authentication',
        'guides/subscriptions',
        'guides/console',
        'guides/portal',
        'guides/observability',
        'guides/hybrid-gateway-adapter',
        'guides/gateway-auto-registration',
        'guides/mcp-getting-started',
        'guides/mcp-tools-development',
        'guides/subscriptions-lifecycle',
        'guides/consumer-onboarding',
        'guides/api-key-rotation',
        'guides/environment-management',
        'guides/multi-gateway-setup',
        'guides/gateway-modes',
        'guides/mtls-configuration',
        'guides/webhooks',
        'guides/service-accounts',
        'guides/console-advanced',
        'guides/portal-advanced',
        {
          type: 'category',
          label: 'Technical Fiches',
          items: [
            'guides/fiches/oauth2-token-exchange',
            'guides/fiches/mcp-protocol',
            'guides/fiches/api-gateway-patterns',
            'guides/fiches/data-sovereignty-gdpr',
          ],
        },
        'guides/opa-policies',
        {
          type: 'category',
          label: 'Migration',
          items: [
            'guides/migration/index',
            'guides/migration/ibm-webmethods',
            'guides/migration/webmethods-sidecar',
            'guides/migration/kong',
            'guides/migration/apigee',
            'guides/migration/oracle-oam',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        description: 'REST API reference for STOA Platform — Control Plane, MCP Gateway, and Gateway Admin APIs.',
      },
      items: [
        'api/control-plane',
        'api/mcp-gateway',
        'api/gateway-admin-api',
        'api/openapi-reference',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/hardware-requirements',
        'reference/performance-benchmarks',
        'reference/benchmark-methodology',
        'reference/configuration',
        'reference/mcp-tools',
        'reference/cli',
        'reference/stoa-yaml',
        'reference/rbac-permissions',
        'reference/oauth-discovery',
        'reference/quotas',
        'reference/security-configuration',
        'reference/exit-strategy',
        'reference/changelog',
        'reference/glossary',
        'reference/troubleshooting',
        {
          type: 'category',
          label: 'Kubernetes CRDs',
          items: [
            'reference/crds/index',
            'reference/crds/tool',
            'reference/crds/toolset',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      link: {
        type: 'doc',
        id: 'architecture/adr/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture/adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: false,
      items: [
        'community/index',
        'community/philosophy',
        'community/rewards',
        'community/contributing',
        'community/faq',
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        'legal/terms',
        'legal/trademarks',
      ],
    },
    'faq/index',
    'roadmap',
  ],
};

export default sidebars;
