// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 CAB Ingénierie / Christophe ABOULICAM
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/architecture',
        'concepts/mcp-gateway',
        'concepts/gitops',
        'concepts/multi-tenant',
        'concepts/mcp-gateway-positioning',
      ],
    },
    {
      type: 'category',
      label: 'Enterprise',
      items: [
        'enterprise/use-cases',
        'enterprise/security-compliance',
        'enterprise/support',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/hybrid',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/quick-start',
        'guides/authentication',
        'guides/subscriptions',
        {
          type: 'category',
          label: 'Migration',
          items: [
            'guides/migration/index',
            'guides/migration/ibm-webmethods',
            'guides/migration/oracle-oam',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/control-plane',
        'api/mcp-gateway',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/configuration',
        'reference/mcp-tools',
        'reference/cli',
        'reference/security-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      link: {
        type: 'doc',
        id: 'architecture/adr/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture/adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsed: false,
      items: [
        'community/index',
        'community/philosophy',
        'community/rewards',
        'community/faq',
      ],
    },
    'faq/index',
    'roadmap',
  ],
};

export default sidebars;
